# Generated by Django 5.0.6 on 2026-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('ventilator', 'Ventilator'), ('maternity', 'Maternity'), ('emergency', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show'), ('escalated', 'Escalated')], default='requested', max_length=20)),
                ('is_emergency', models.BooleanField(default=False)),
                ('condition_category', models.CharField(blank=True, max_length=100)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('patient_latitude', models.FloatField(blank=True, null=True)),
                ('patient_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
