# Generated by Django 5.0.6 on 2026-07-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
