# Generated by Django 5.0.6 on 2026-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_fraud_flags_booking_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='previous_hospital_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
