# Generated by Django 5.0.6 on 2026-07-05 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport')], max_length=20)),
                ('encrypted_file', models.FileField(upload_to='identity_documents/%Y/%m/')),
                ('name_on_document', models.CharField(max_length=255)),
                ('name_match_result', models.CharField(choices=[('exact_match', 'Exact Match'), ('close_match', 'Close Match'), ('mismatch', 'Mismatch — Needs Review')], max_length=20)),
                ('name_match_score', models.FloatField()),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
